import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Mumair",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html  lang="en"
    className=" flex lg:items-center lg:justify-center w-full scroll-smooth">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
